insert into product (name, description, image, price) values ("Anvil", "For blacksmithing or bird smashing", "img/1.jpg", 109.99);
insert into product (name, description, image, price) values ("Axle Grease", "Great for a slippery situation", "img/2.jpg", 8.98);
insert into product (name, description, image, price) values ("Atom Re-Arranger", "No one liked atoms in that arrangment anyway", "img/3.jpg", 55.66);
insert into product (name, description, image, price) values ("Bed Springs", "How high can you bounce?", "img/4.jpg", 2.79);
insert into product (name, description, image, price) values ("Bird Seed", "Literally bird seed", "img/5.jpg", 1.99);
insert into product (name, description, image, price) values ("Blast Powder", "For all of your bomb making needs", "img/6.jpg", 12.45);
insert into product (name, description, image, price) values ("Cork", "For the immediate plugging of any hole", "img/7.jpg", 9.99);
insert into product (name, description, image, price) values ("Disintegration Pistol", "Set phasers to disappear", "img/8.jpg", 549.99);
insert into product (name, description, image, price) values ("Earthquake Pills", "Shake, Rattle and Roll", "img/9.jpg", 15.15);
insert into product (name, description, image, price) values ("Female Roadrunner Costume", "For those secret weekend parties", "img/10.jpg", 79.97);
insert into product (name, description, image, price) values ("Giant Rubber Band", "Perfect for your giant slingshot", "img/11.jpg", 20.19);
insert into product (name, description, image, price) values ("Instant Girl", "The opposite of Slow Girl", "img/12.jpg", 88.88);
insert into product (name, description, image, price) values ("Iron Carrot", "Fortified for your health", "img/13.jpg", 19.49);
insert into product (name, description, image, price) values ("Jet Propelled Unicycle", "And you thought unicycles were boring", "img/14.jpg", 115.99);
insert into product (name, description, image, price) values ("Out-Board Motor", "Great for your next fishing trip", "img/15.jpg", 256.45);
insert into product (name, description, image, price) values ("Railroad Track", "Fake tunnel opening sticker not included", "img/16.jpg", 14.99);
insert into product (name, description, image, price) values ("Rocket Sled", "Make sledding dangerous again", "img/17.jpg", 45.11);
insert into product (name, description, image, price) values ("Super Outfit", "Make Super Man jealous", "img/18.jpg", 79.49);
insert into product (name, description, image, price) values ("Time Space Gun", "Not to be confused with the Spacetime gun", "img/19.jpg", 999.99);
insert into product (name, description, image, price) values ("X-Ray", "Oof ouch my bones", "img/20.jpg", 666.66);